"""One-shot historical backfill of TB snapshots.

Computes month-end of each of the last N months and calls
refresh_tb_snapshot() for each. After successful refresh on a past
date, immediately marks is_immutable=1 so the snapshot cannot be
silently regenerated by a subsequent scheduler tick.

Safety check: refuses to run if 12 * COUNT(tabGL Entry) exceeds 10M
rows (rough upper bound for total rows scanned during a 12-month
backfill). Override with force=True.
"""

import time
from calendar import monthrange
from datetime import date

import frappe
from frappe import _
from frappe.utils import getdate, today

from dux_groupview.dux_groupview.snapshots.refresh import refresh_tb_snapshot


SAFETY_ROW_THRESHOLD = 10_000_000


def backfill_snapshots(months_back=12, force=False):
	"""Backfill the last N month-end snapshots.

	Args:
		months_back: number of past month-ends to compute. Defaults to 12.
		force: if True, skip the safety check and regenerate even
			already-immutable snapshots.

	Returns:
		dict with keys: dates_processed (list of {date, status,
		row_count, duration_seconds}), skipped (list of dates).
	"""
	months_back = int(months_back)
	if months_back < 1:
		frappe.throw(_("months_back must be at least 1."))

	today_d = getdate(today())
	dates = _month_end_dates(today_d, months_back)

	# Safety check.
	gl_count = frappe.db.count("GL Entry")
	estimated = gl_count * months_back
	if estimated > SAFETY_ROW_THRESHOLD and not force:
		frappe.throw(
			_(
				"Backfill safety check tripped: estimated {0:,} GL Entry rows "
				"would be scanned across {1} month-end snapshots "
				"(threshold {2:,}). Re-run with force=True to override."
			).format(estimated, months_back, SAFETY_ROW_THRESHOLD)
		)

	print(f"Backfilling {len(dates)} month-end snapshots...")

	processed = []
	skipped = []

	for i, d in enumerate(dates, 1):
		# Check immutability before doing work.
		existing = frappe.db.get_value(
			"DGV TB Snapshot",
			{"snapshot_date": d},
			["name", "is_immutable"],
			as_dict=True,
		)
		if existing and existing.is_immutable:
			if not force:
				print(f"  [{i}/{len(dates)}] {d} skipped (already immutable)")
				skipped.append(str(d))
				continue
			# force=True: clear the lock so refresh_tb_snapshot will run.
			# The lock is re-applied below after the refresh succeeds.
			frappe.db.set_value(
				"DGV TB Snapshot", existing.name, "is_immutable", 0
			)
			frappe.db.commit()

		t0 = time.time()
		try:
			result = refresh_tb_snapshot(snapshot_date=d)
		except Exception as e:
			print(f"  [{i}/{len(dates)}] {d} FAILED: {e}")
			processed.append({
				"date": str(d),
				"status": "Failed",
				"error": str(e),
			})
			continue

		# Lock past dates immediately so the next scheduler tick can't
		# silently overwrite them.
		if d < today_d:
			frappe.db.set_value(
				"DGV TB Snapshot",
				result["snapshot_name"],
				"is_immutable",
				1,
			)
			frappe.db.commit()

		print(
			f"  [{i}/{len(dates)}] {d} done in "
			f"{time.time() - t0:.1f}s "
			f"({result['row_count']:,} rows)"
		)
		processed.append({
			"date": str(d),
			"status": "Complete",
			"row_count": result["row_count"],
			"duration_seconds": result["duration_seconds"],
		})

	print(
		f"Backfill complete: {len(processed)} processed, "
		f"{len(skipped)} skipped."
	)
	return {"dates_processed": processed, "skipped": skipped}


def _month_end_dates(reference_date, months_back):
	"""Return the last N month-end dates strictly preceding reference_date.

	Months are counted by calendar months, not 30-day chunks. The current
	month's end is included only if reference_date is strictly less than
	the current month's last day; otherwise we include the previous N
	month-ends.
	"""
	results = []
	year = reference_date.year
	month = reference_date.month

	# Walk back month-by-month.
	for _i in range(months_back):
		# Compute month-end of current (year, month).
		last_day = monthrange(year, month)[1]
		month_end = date(year, month, last_day)
		# Only include if strictly before reference_date.
		if month_end < reference_date:
			results.append(month_end)
		# Step back one month.
		month -= 1
		if month == 0:
			month = 12
			year -= 1

	# Ensure we have exactly months_back items even if today is mid-month.
	# Walk back further if needed.
	while len(results) < months_back:
		last_day = monthrange(year, month)[1]
		results.append(date(year, month, last_day))
		month -= 1
		if month == 0:
			month = 12
			year -= 1

	# Sort oldest first so the print log reads naturally.
	results.sort()
	return results[-months_back:]
